### ISSUE TITLE
Missing replace.php and header.php

### ISSUE THREAD

**Issue by bartleph** [peterkvt80/makenews#4]
Where can I find the two missing include files (replace.php and header.php) ??
When having to load PHP the version is 8.2 and there are quite a few changes to be corrected.

**Comment by peterkvt80** [comment]
This project has been abandoned a long time. I should really delete it. The main problem is that the BBC regularly change their website format so that extracting the information requires regular tweaks. Nathan Dane took over many years ago and maintains his own code although I don't know if it is open source. His viewer is here: https://www.nathanmediaservices.co.uk/ceefax/#id=WyJubXMtY2VlZmF4IiwiaW50ZXJuYWwubmF0aGFubWVkaWFzZXJ2aWNlcy5jby51ayIsIi93ZWJzb2NrZXRzL2NlZWZheCJd:page=100

**Comment by bartleph** [comment]
Thank you for your reply Peter.
